export const SET_THEME = "SET_THEME";
export const SET_INTERFACE_ENTRY = "SET_INTERFACE_ENTRY";
export const SET_REPORT_DATA_AND_HEADERS = "SET_REPORT_DATA_AND_HEADERS";
export const SET_REPORT_PARAMETERS = "SET_REPORT_PARAMETERS";
